# SPDX-FileCopyrightText: Copyright 2025 Framna Netherlands B.V., Zwolle, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: General Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  ec-checker:
    uses: lunr-php/actions-templates/.github/workflows/ec-checker.yml@826ca60a8afd857beead02ab5b6f6a44a707650c # 0.12.0
    with:
      excludes: '.*\.php$'
  reuse:
    uses: lunr-php/actions-templates/.github/workflows/reuse.yml@826ca60a8afd857beead02ab5b6f6a44a707650c # 0.12.0
  typos:
    uses: lunr-php/actions-templates/.github/workflows/typos.yml@826ca60a8afd857beead02ab5b6f6a44a707650c # 0.12.0
    with:
      config: tests/typos.toml
