# SPDX-FileCopyrightText: Copyright 2025 Framna Netherlands B.V., Zwolle, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: PHP Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  php-tests:
    uses: lunr-php/actions-templates/.github/workflows/php-library.yml@826ca60a8afd857beead02ab5b6f6a44a707650c # 0.12.0
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      coding-standard: 'Lunr'
      minimum-php-version: '8.3'
      phpcs-whitelist: tests/phpstan.bootstrap.inc.php tests/test.bootstrap.inc.php
      php-extensions: uopz, uuid
      stable-php-versions: '["8.3"]'
      experimental-php-versions: '["8.4","8.5"]'
